webtalk_init -webtalk_dir C:/harman/FPGA_Harman/I2C_Slave/I2C_Slave.sim/sim_1/behav/xsim/xsim.dir/tb_I2C_Slave_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Sat May 24 14:02:22 2025" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2020.2 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "3064766" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "fd134540-188b-44cb-b9b0-9ac884800217" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "4c6342f6e5854f94a1eec6968f73fcab" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "239" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Windows Server 2016 or Windows 10" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "12th Gen Intel(R) Core(TM) i5-12400F" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2496 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "16.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key runall -value "true" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "641035 ns" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "0" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.09_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "17548_KB" -context "xsim\\usage"
webtalk_transmit -clientid 3675512769 -regid "" -xml C:/harman/FPGA_Harman/I2C_Slave/I2C_Slave.sim/sim_1/behav/xsim/xsim.dir/tb_I2C_Slave_behav/webtalk/usage_statistics_ext_xsim.xml -html C:/harman/FPGA_Harman/I2C_Slave/I2C_Slave.sim/sim_1/behav/xsim/xsim.dir/tb_I2C_Slave_behav/webtalk/usage_statistics_ext_xsim.html -wdm C:/harman/FPGA_Harman/I2C_Slave/I2C_Slave.sim/sim_1/behav/xsim/xsim.dir/tb_I2C_Slave_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
